### ISSUE TITLE
Cannot compile example program

### ISSUE THREAD

**Issue by Beliavsky** [red0124/ssp#14]
I installed ssp on Windows Subsystem for Linux but cannot compiler the example program: What compiler options do I need?

bingy@DESKTOP-O9ELSIT:/mnt/c/cpp/public_domain/ssp/include$ cat try.cpp
cat try.cpp
```
#include <iostream>
#include <ss/parser.hpp>

int main() {
	ss::parser p{"students.csv", ","};

	for(auto& [name, age, grade] : p.iterate<std::string, int, double>()) {
		if (p.valid()) {
			std::cout << name << ' ' << age << ' ' << grade << std::endl;
		}
	}

	return 0;
}

```
bingy@DESKTOP-O9ELSIT:/mnt/c/cpp/public_domain/ssp/include$ g++ try.cpp
g++ try.cpp
In file included from /usr/local/include/ss/converter.hpp:2,
                 from /usr/local/include/ss/parser.hpp:4,
                 from try.cpp:2:
/usr/local/include/ss/extract.hpp:20:23: error: ‘is_floating_point_v’ is not a member of ‘std’; did you mean ‘is_floating_point’?
   20 | std::enable_if_t<std::is_floating_point_v<T>, std::optional<T>> to_num(
      |                       ^~~~~~~~~~~~~~~~~~~
      |                       is_floating_point
/usr/local/include/ss/extract.hpp:20:23: error: ‘is_floating_point_v’ is not a member of ‘std’; did you mean ‘is_floating_point’?
   20 | std::enable_if_t<std::is_floating_point_v<T>, std::optional<T>> to_num(
      |                       ^~~~~~~~~~~~~~~~~~~
      |                       is_floating_point

**Comment by red0124** [comment]
It only works for c++17 and above, and since c++14 is the default standard (I think) you need to add **-std=c++17** when compiling.

**Comment by Beliavsky** [comment]
Thanks, it compiles and runs with -std=c++17.
