### ISSUE TITLE
How to get the header row?

### ISSUE THREAD

**Issue by ludeen007** [red0124/ssp#45]
Thank you for providing a great library.

I want to get the header row of a .csv file  which has unknown fields, how to do it?

**Comment by red0124** [comment]
I am glad you find the library useful.

At the moment you can only check if the header contains a field using the `field_exists` method. If you need a method which returns, for example, an `std::vector<std::string>>` containing all the fields, I could add it, I see that it might be useful in some situations.

**Comment by red0124** [comment]
The library now offers some methods to meet the requirements, starting from version 1.8.0.
